### ISSUE TITLE
EnsembleOut should initialize metadata

### ISSUE THREAD

**Issue by xjules** [equinor/ert-storage#102]
`metadata` property is not set when creating EnsembleOut.

**Comment by dotfloat** [comment]
We're currently creating a lot the pydantic models manually and we shouldn't be doing that. The whole point is that you return an SQLAlchemy object and pydantic is able to convert. So I think the issue shouldn't be to initalise metadata in one place, but to refactor and make sure that the rest of the system behaves consistently.

**Comment by xjules** [comment]
This can be closed as solved in https://github.com/equinor/ert-storage/pull/105.
