### ISSUE TITLE
GraphQL `Metadata` fields are nullable, when they should be empty dicts

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert-storage#117]
If one requests the `Metadata` field when `_metadata` is `NULL` in the database, the `Metadata` field will also be `null`. This goes against the convention that we've decided, where a `NULL` metadata is exposed to the user as `{}`.

The solution can be to add a GraphQL field called `metadata` (lowercase 'm'), which returns `root.metadata_dict` where necessary. Should also look into how to avoid exposing fields automatically when using `SQLAlchemyObjectType` (or maybe not use it at all?)

**Comment by xjules** [comment]
Can we make `metadata={}` by default?
`_metadata = sa.Column("metadata", sa.JSON, default={})`
