### ISSUE TITLE
Make integration tests

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert-storage#127]
1. Enable the komodo integration testing in some pipeline running tests on the deployed versions
2. Enable new-storage on HM tutorial ( not main pipeline - should be a new or attached to another one not blocking a release if failing ) 
3. Assert data using ERT storage instead of EnkfMain
4. Make integration test that are running ERT -> ERT storage -> webviz ERT using i.e SPE1

**Comment by sondreso** [comment]
See: https://github.com/equinor/scout/issues/386
