### ISSUE TITLE
Visualize data from ERT using EnkfMain as backend through ert-storage

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert-storage#146]
Definition of done
- A user should be able to visualize data in webviz-ert by pointing to a config file
- This should be production ready on-premise
- Compared to the old qt plotter - the performance should be comparable on a realistic case on an RGS node using NFS
- HM-tutorial running visualizing data in webviz-ert through this new backend
- All of the data in the cases in the storage that the config is pointing at should be included
- The observation data the config is pointing towards should be included
- No new plugins in webviz-ert. No new visualizations.
- Running ert with new storage enabled - webviz-ert should look the same when visualizing data through the db and the enkf-main backend ( possible exception, relationships between cases )

Nice to have
- The new backend running on top of old storages

**Comment by markusdregi** [comment]
The work has been completed.
