### ISSUE TITLE
Should we store relational data in the file storage?

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert-storage#153]

**Comment by dotfloat** [comment]
We should avoid it as much as possible. Adding sqlite adds a lot of complexity and headache as we've learned over the past few months.

For the moment we can fetch relational data from EnKFMain or keep it in a dict:
1. We're looking to have a single worker on a single machine, with no horisontal scaling. If we end up with multiple workers then we can share data via POSIX shared memory. (eg, how `multithreading` works)
2. UUIDs can be generated at startup and not persisted. Webviz-ERT doesn't cache UUIDs anywhere except in memory, and we don't expect it to outlive the storage server.

**Comment by markusdregi** [comment]
Should we close this due to the same reasons as: https://github.com/equinor/ert/issues/2032?
