### ISSUE TITLE
How to interact with webviz-ert? How to launch?

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert-storage#154]

**Comment by dotfloat** [comment]
Current approach I'm working on is to change `ert api` and `ert vis` to default to Dark Storage. Running either in a directory with a single `.ert` file will use it. If there are multiple, the user can provide the specific config: `ert api poly.ert`.

The old functionality is available via `ert api --database-url=sqlite://ert.db`. Any command using `--enable-new-storage` will be unaffected, and use the proper ERT Storage.

**Comment by markusdregi** [comment]
Since all real life examples will operate in a folder with multiple configuration files I think we might as well require the configuration to be specified. No need to introduce the deduction of configuration as long as it will never be used by any user :)
