### ISSUE TITLE
Fix breaking changes in azure-storage-blob 12.9 

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert-storage#159]
`azure-storage-blob` in `src/ert_storage/database.py` is imported if an azure url is present. They have just released version 12.9 which breaks the api and we need to adapt. This issue is to fix the changes and also bump the version of the package in komodo. For now i've pinned the version < 12.9 in ert-storage `setup.py`

**Comment by dotfloat** [comment]
Not our fault. Blocked by https://github.com/Azure/azure-sdk-for-python/issues/20771

**Comment by oysteoh** [comment]
This is fixed and the version is no longer pinned
