### ISSUE TITLE
Initial `ert_storage.client`

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert-storage#166]
We will need a client to avoid duplicating code. In the first iteration, we should just expose an already-configured `requests.Session` object.

Usage:
```py
from ert_storage.client import Session

with Session() as session:
    session.get("/experiments")
```

`Session` uses a `ERT_STORAGE_CONNECTION_STRING` environment variable, much like Azure client does, to determine where to connect and which token to use. This environment variable is set by ERT for each forward-model job.

Here's how we create a pre-configured `Session` object in ERT: https://github.com/equinor/ert/blob/e0d5046b4135c1fbbcee27ee40c64eacc44289fc/ert_shared/services/storage_service.py#L70-L78

The `client` subpackage can be its own PyPI package if we care that much, just like `azure-blob-storage` is a separate package, but in the same repository as all the other Azure Python bindings.

**Comment by TerryHannant** [comment]
Couple initial questions:
What should the config failure behavior be for Session, Ie missing env?
Do we want the client to emulate the current "connect" timeout behavior?

**Comment by dotfloat** [comment]
This client should be as simple as possible. As such, we can start with the following behaviour:
1. Die if it can't immediately find the `storage_server.json` file or `ERT_STORAGE_CONNECTION_STRING` envvar when that is done.
2. Don't poll. We assume that the server is up and running.
