### ISSUE TITLE
Improve the storage-client

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert-storage#181]
The storage client should be improved. We should only check the url's at startup  ( and maybe if there is a connection error at some point ).

**Comment by frode-aarstad** [comment]
Also it would be nice to be able to initialize it with parameters like:

`Session(base_url=base_url, headers={"Token": token})`

This would make it easier to replace https://github.com/equinor/ert/blob/be5cb726ff67e73a579a5c45806d6b3330e517c5/ert_shared/services/storage_service.py#L70-L78

**Comment by dotfloat** [comment]
I will be adding unix socket support as well
