### ISSUE TITLE
Improve parameter label fetching

### ISSUE THREAD

**Issue by DanSava** [equinor/ert-storage#204]
**Issue**
User feedback for webviz-ert pointed out that if we are dealing with a case with numerous parameters there will be a lot of API calls to fetch possible parameter `labels`

**Describe the solution you'd like**
Return parameter labels together with names when getting the ensemble parameters.

**Describe alternatives you've considered**
* Add API endpoint to retrieve all parameters together with labels if they exist. 
* Update ensemble schema to accommodate not only parameter names but also possible labels

**Comment by markusdregi** [comment]
Related to: https://github.com/equinor/ert/issues/2838
