### ISSUE TITLE
Update storage client so that it can be used from ert 

### ISSUE THREAD

**Issue by DanSava** [equinor/ert-storage#205]
**Issue**

I might be off in my assumption that the ert_storage Client was designed to be used from `ert` other consumers of the package. But using it from ert is not really straightforward.

It is not possible to use the client similar to the example below:

``` python
from ert_storage import  Client

with Client() as client:
   experiments  = client.get("/experiments").json()
```
This is because the connection information stored in the file `storage_server.json` si formatted like:

```
{"authtoken": "test123", "urls": ["url1", "url2"]}
```
but ert_storage Client expects either the file to be formatted as:

```python 
{ "base_url": "url1", "auth_token": "test124"}
```
of the env variable `ERT_STORAGE_CONNECTION_STRING` to be set with the same information which does not seem to be the case.

**Comment by frode-aarstad** [comment]
It should be possible to write something like this:
``` 
from ert_shared.services import Storage

 with Storage.session() as session:
   exp=  session.get("/experiments")
```
Does this provide you with the functionality you look for @DanSava ?

**Comment by DanSava** [comment]
Yes, it provides the functionality I am looking for, that is what I ended up using in the API case name PR. 

But I thought that the point of the client was to be used as I was describing in the issue 

``` python
from ert_storage import  Client

with Client() as client:
   experiments  = client.get("/experiments").json()
```

if the point was to never use it directly and always use a session to wrap it, then it is fine as it is and we should close this issue.

**Comment by frode-aarstad** [comment]
I think the intended approach is to use the session. Perhaps @pinkwah has any thoughts on this ?

**Comment by DanSava** [comment]
Using Session is fine by me.

I still think that a session should be provided by the storage client and not be required to be implemented in the consumer in this case ERT, but anyways I think it is good enough.
