### ISSUE TITLE
Introduce experiments in relational db

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert-storage#21]
Enable experiments holding multiple ensembles to be defined in the database.
Should include:
- name
- ensembles
- ...?

**Comment by jondequinor** [comment]
At some point an update algorithm will be selected, but the algorithm will probably need its own relation.

**Comment by dotfloat** [comment]
The main thing about experiments is that they'll act as an anchor to which all the user configuration will refer to. I think it's enough to just start out with a very dumb table containing `id`s. Later on, when we store snapshots of the user config, they'll have a `experiment_id` column.
