### ISSUE TITLE
Make compatible with fastapi>=0.89

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert-storage#232]
Changes in Response from 0.89 causing following error which needs to be fixed
```
fastapi.exceptions.FastAPIError: Invalid args for response field! Hint: check that <class 'starlette.responses.Response'> is a valid pydantic field type
Error: Process completed with exit code 1.
```

**Comment by andreas-el** [comment]
Using packages:
FastAPI: 0.92.0
Starlette: 0.25.0
The test_dark_storage_performance.py do not raise this exception anymore.

**Comment by andreas-el** [comment]
Also, verified that version 0.89 of FastAPI was incompatible with currently used version 0.20.4 of Starlette.
