### ISSUE TITLE
Using the same codebase and database for both new and newnew storage

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert-storage#39]

**Comment by markusdregi** [comment]
I think we should add a definition of done...

Some suggested criteria:
- Run the poly case & HM tutorial using ert and visualise data using webviz-ert afterwards
- Delete `ert_shared.storage` from the ert repository
- Run all ert(3) tests successfully with ert-storage as storage
- Run the ert3 examples and visualise data using webviz-ert afterwards

**Comment by dotfloat** [comment]
Yeup. If we can delete `ert_shared.storage` and lose no functionality then this issue can be closed.

**Comment by markusdregi** [comment]
If we can delete `ert_shared.storage` and lose no functionality and in addition the consumers `ert`, `ert3` and `webviz-ert` have somewhat unified consumption of `ert-storage` I agree 👍🏻 Perhaps a good test for this is that `webviz-ert` can visualise an `ert3` run? That was at least my motivation for including the last point above...
