### ISSUE TITLE
Migrate parameters

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert-storage#47]
This can probably be implemented together with #42 

- Same as responses - use a `Record` with the type `Parameter`

**Comment by ManInFez** [comment]
In ert3 we have a notion of parameters, as a list of records used as inputs for an ensemble. ert2 have a very specialised parameter table, which connect to Priors. Should priors be a metadata in the first iteration?

**Comment by ManInFez** [comment]
This is a wont fix
