### ISSUE TITLE
Migrate to using UUIDs instead of incremental integer IDs

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert-storage#52]
The returned `"id"` values should also be `str` rather than `int` as they are now. From the user's perspective, the IDs are opaque objects rather than numeric, and this should be evident in the type system and JSON types.

One reason for doing this is that it will help debugging. As we normally run tests from an in-memory SQLite database, the integer IDs start from 1. Thus it is difficult to notice that two objects are different just from looking at their IDs, as if they're from two different tables, they are likely to have the same integer value.

**Comment by oysteoh** [comment]
should we still use the  incremental `int` as primary key and just add a `uuid` column, or do we want to have the `uuid` as primary and only identifier?

**Comment by ManInFez** [comment]
`
CREATE TABLE users(
  pk INT NOT NULL AUTO_INCREMENT,
  id UUID NOT NULL,
  .....
  PRIMARY KEY(pk),
  UNIQUE(id)
);
`

It seems that primary key as an autoincrement is the way to go, and then include a unique uuid which can then be exposed to the users. It will affect how we use `query.(<table>).get(<pk>)`
