### ISSUE TITLE
Metadata and ObservationTransformation

### ISSUE THREAD

**Issue by xjules** [equinor/ert-storage#60]
This needs to be discussed whether `ObservationTransformation` should have their own metadata too.

**Comment by dotfloat** [comment]
Imo, we should wait with a discussion until there's something that's actively using `ObservationTransformation`s. Eg, `webviz-ert`.

**Comment by oysteoh** [comment]
Closing for now as it is not needed. When we start implement and we see the usage of this we will make new issue.
