### ISSUE TITLE
Getting observations for the initial ensemble (without previous update) seems to have a nullpointerexception

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert-storage#62]
Line 75 looks sus, since `update` would be `None`.

https://github.com/equinor/ert-storage/blob/c84700382fe440dda4fbe4cddd7766860f673deb/ert_storage/endpoints/observations.py#L70-L78

**Comment by markusdregi** [comment]
@dotfloat: Steps to reproduce would be nice 👍🏻

**Comment by dotfloat** [comment]
1. Make experiment
2. Make ensemble for experiment
3. Get this endpoint (`/ensembles/{ensemble_id}/observations`)
4. Observe `NoneType` error because `update` is `None` (there is no parent, this is the first iteration), but we're getting the `observation_transformations` attribute.

**Comment by ManInFez** [comment]
This has already been fixed by this line: https://github.com/equinor/ert-storage/blob/062a01742f0f4aa3bfa655a3a31fe8ca3d87b0cd/ert_storage/endpoints/observations.py#L80
