### ISSUE TITLE
Add mismatch detection in observation treatment 

### ISSUE THREAD

**Issue by xjules** [equinor/ert-storage#72]
We should handle mismatch between observations and responses in the following scenarios:

- when adding new observations to a record (check that those observations have the corresponding values)
- when using observations for computations (like for instance the misfits endpoint) report that the observations are missing the corresponding response values

Further read: https://github.com/equinor/ert-storage/issues/69

**Comment by markusdregi** [comment]
Are we sure this should be the responsibility of `ert-storage`?

**Comment by dotfloat** [comment]
I think it makes sense for ERT Storage to verify that the data is consistent, and reject data that isn't, as long as the algorithm for verifying this is in PTIME and is relatively easy to implement. It applies in this case.

Basically, the more guarantees we can make to the clients of ERT Storage, the better. Makes for a better API.

**Comment by markusdregi** [comment]
I agree on the specific topic of requesting misfits. But, unless the observations are inherently tied to certain ensembles (which I have argued they should not be), then I don't think `ert-storage` can take full responsibility for this. At least not on `ensemble` and `observation` level. It is most likely feasible on a history matching experiment level, but then again I'm not entirely sure whether this should be the responsibility of storage. What if the user decides on an interpolation strategy; is ert-storage then to know about this?

**Comment by dotfloat** [comment]
We can do the strict thing by default and then the user can specify that they want to have interpolation and then we ignore it mismatches. Also, I don't think it makes sense to do it when posting an observation, but when posting a response.

This issue could be closed as "would be nice but we don't want to spend effort on it" if you want.

**Comment by markusdregi** [comment]
Then I close it as "Will not be addressed for now and will most likely be outdated when we want to do this"
