### ISSUE TITLE
Interpolation strategy for responses

### ISSUE THREAD

**Issue by xjules** [equinor/ert-storage#74]
A placeholder to discuss strategies for response interpolation; ie. their endpoints, types, etc.
Relevant reading can be found here: https://github.com/equinor/ert-storage/issues/69

**Comment by dotfloat** [comment]
For future discussion, but I was thinking that we could have a `?interpolate=nearest` and such for a list of common interpolation methods when fetching the data. A record can be marked with interpolable when POSTing, and then we don't do checking on whether its indices match the relevant observation group's indices.

**Comment by mortalisk** [comment]
It seems that it was decided in #69 that we won't do interpolation in storage, so this seems irrelevant. Closing.
