### ISSUE TITLE
Make RecordType be a ENUM

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert-storage#77]
Currently the `record_type` is a integer column with a hacky conversion to and from `enum.Enum`, rather than an enum column like `record_class`. We should convert it to the same mechanism as `record_class`.

**Comment by sondreso** [comment]
What record types do you currently have?

**Comment by dotfloat** [comment]
https://github.com/equinor/ert-storage/blob/660694a36fb56808f9645220b3d877b6c880c439/ert_storage/database_schema.py#L16-L18

* `float_vector` is an arbitrary dimensional float matrix with optional string labels.
* `file` is an arbitrary blob.
