### ISSUE TITLE
Delete source directory on Github Actions before running tests

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert-storage#78]
We `pip install` the package correctly, however `pytest` will add the incorrect source directory to `sys.path`. Delete the sources like we do on other projects.

**Comment by markusdregi** [comment]
Or alternatively introduce a `src` folder at the root of the repository...

**Comment by dotfloat** [comment]
I'm not against this idea, but it could break PyCharm. Check in with @oysteoh before mergin such a PR.

**Comment by markusdregi** [comment]
That would surprise me as it is a standard thing to do in the Python community. But I agree it is worth checking :)

**Comment by dotfloat** [comment]
PyCharm doesn't `pip install -e` your software and instead uses `PYTHONPATH` for everything. It could be that the maintainers of repositories that use `src` don't use PyCharm or have to configure it every time to do the correct thing.

**Comment by markusdregi** [comment]
Color me impressed

**Comment by jondequinor** [comment]
For some important arguments for `src`, see https://blog.ionelmc.ro/2014/05/25/python-packaging/

> The src directory is a better approach because:
> - You get **import parity**. The current directory is implicitly included in sys.path; but not so when installing & importing from site-packages. Users will never have the same current working directory as you do.
