### ISSUE TITLE
Implement simple interface for getting ensemble related metadata 

### ISSUE THREAD

**Issue by xjules** [equinor/ert-storage#91]
The idea is to have a simple (graphQL) interface to retrieve all the metadata important for webviz-ert to fill out all the GUI elements.

Create new issues out of this whenever picking it up - making concrete issues which can be solved one by one.

Do metadata listing for:
- Ensemble
- Parameter
- Response
- Observation

**Comment by xjules** [comment]
Is this epic still required? I would close it otherwise.

**Comment by mortalisk** [comment]
I think we close this
